// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mootaz_UpdateQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mootaz_UpdateQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201911052314207_Mootaz_UpdateQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
